CREATE DATABASE RESERVATION;

USE RESERVATION;

CREATE TABLE USER(
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    EMAIL VARCHAR(20),
    PASSWORD VARCHAR(50),
    PRIMARY KEY (ID),
    UNIQUE KEY (EMAIL)
)